### ISSUE TITLE
Failed to load example

### ISSUE THREAD

**Issue by subtiv** [vade/ofxQCPlugin#1]
Hi There,

I was unable to run the examples of this great addon. Maybe I'm doing something wrong, however I've looked through all the obvious.

Settings:
Xcode 5.1.1
osx 10.9.3

Project Settings:
i386
SDK:10.8
(Building creates the QCPlugin and installs it appropriatly in ~/Graphics/Quartz Composer Plugins)

OF settings:
osx_8.3
i386
SDK:10.8

Additional; I'm able to create QCPlugins using the default apple template

**Comment by vade** [comment]
Be sure you launch Quartz Composer in 32 bit, as (for now) oF and thus ofxQCPlugIn is 32 bit only.

**Comment by subtiv** [comment]
Ow sh*t, I thought the 32bit stuff was regarding the OF-build. Sorry to bother! 
Works like a charm, thanks
