### ISSUE TITLE
plugin cannot draw

### ISSUE THREAD

**Issue by badgeek** [vade/ofxQCPlugin#2]
hi, the plugin worked great with ofImage to qc but when i tried to draw some rectange to testapp::draw()  it doesnt work at all just blank screen

thanks

**Comment by vade** [comment]
Yea this hasn't been updated for the newer oF in a while, a lot of their internal OpenGL state has changed, and it hasn't been updated. What version of oF are you using with this? 

Did you change the plugin so its a consumer, doesnt have an image output port and all the appropriate QC stuff?

**Comment by badgeek** [comment]
im using 0.8.4, i just add some rectangle to the draw function in your ofImage to qc example, what is the current supported oF version?

**Comment by vade** [comment]
Well, so there are lots of issues in OpenFrameworks, like face culling issues and what not, where drawing primitives have the wrong winding order that can cause all sorts of issues with the OpenGL pipeline and 'corrupting' the expected state of QC vs OpenFrameworks.

https://github.com/openframeworks/openFrameworks/issues/2676

So I'm really unsure what to tell you without you actually being way more explicit about what you are doing.

**Comment by vade** [comment]
Well, you didn't need to close this, I'm not sure if its a winding order, or an OF issue, there are probably workarounds...
